apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-bff-web-inventory
  namespace: local-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-bff-web-inventory
  template:
    metadata:
      labels:
        app: demo-bff-web-inventory
    spec:
      containers:
        - name: demo-bff-web-inventory-container
          image: demo-bff-web-inventory:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "300m" # 1000m = 1 CPU core
              memory: "256Mi" # 256 megabytes, 512 megabytes, 768 megabytes, 1024 megabytes
            requests:
              cpu: "150m"  # 0.75 CPU cores
              memory: "128Mi"  # 256 megabytes, 512 megabytes, 768 megabytes, 1024 megabytes 
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_SERVLET_CONTEXTPATH
              value: "/n86e5252c4bve2egkraw"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://demo-store-db:5433/store"
            - name: SPRING_DATASOURCE_USERNAME
              value: "dbusername"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "dbpassword"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "none"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.postgresql.Driver"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-bff-web-inventory
  namespace: local-cicd
spec:
  selector:
    app: demo-bff-web-inventory
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
  type: ClusterIP # You can use other types like NodePort or LoadBalancer if needed