apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-zookeeper
  namespace: local-cicd
  labels:
    app: demo-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-zookeeper
  template:
    metadata:
      labels:
        app: demo-zookeeper
    spec:
      containers:
        - name: demo-zookeeper
          image: confluentinc/cp-zookeeper:7.0.1
          ports:
          - containerPort: 2181
          resources:
            limits:
              cpu: "600m"  # 0.75 CPU cores
              memory: "512Mi"  # 256 megabytes, 512 megabytes, 768 megabytes, 1024 megabytes 
            requests:
              cpu: "300m" # 1000m = 1 CPU core
              memory: "256Mi" # 256 megabytes, 512 megabytes, 768 megabytes, 1024 megabytes
          env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
          - name: ZOOKEEPER_TICK_TIME
            value: "2000"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-zookeeper
  namespace: local-cicd
spec:
  selector:
    app: demo-zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181