kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-mongodb
  namespace: local-cicd
  labels:
    app: demo-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-mongodb
  template:
    metadata:
      labels:
        app: demo-mongodb
    spec:
      containers:
        - name: demo-mongodb
          image: mongo:6.0.6
          command:
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
          ports:
            - containerPort: 27017
          resources:
            limits:
              cpu: "300m" # 1000m = 1 CPU core
              memory: "256Mi" # 256 megabytes, 512 megabytes, 768 megabytes, 1024 megabytes
            requests:
              cpu: "150m"  # 0.75 CPU cores
              memory: "128Mi"  # 256 megabytes, 512 megabytes, 768 megabytes, 1024 megabytes 
---
apiVersion: v1
kind: Service
metadata:
  name: demo-mongodb
  namespace: local-cicd
spec:
  selector:
    app: demo-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
